import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Fetch from '../components/Fetch'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Testiranje <a href="https://nextjs.org">Nekretnina!</a>
        </h1>

        <p className={styles.description}>
          Fetching data from xml endpoint<br />
          <code className={styles.code}>https://dimedia-nekretnine.nekretninebrcko.com/synchronization_data/web/xml.xml</code>
        </p>

        <Fetch />
      </main>
      <footer className={styles.footer}>#sasa10g</footer>
    </div>
  )
}
